nome = str(input('Digite o nome completo: ')).strip()
print('O nome em maiúscula fica: {} '.format(nome.upper()))
print('O nome em minúscula fica: {} '.format(nome.lower()))
print('Seu nome tem ao todo: {} letras.' .format(len(nome)-nome.count(' ')))
print('Seu primeiro nome tem {} letras.' .format(nome.find(' ')))
separa = nome.split()
print(separa)
print('Seu primeiro nome é {} e ele tem {} letras.' .format(separa[0], len(separa[0])))
